"""
Data models for the SportsSummaryAgent module.
"""

from datetime import date, datetime
from typing import Literal

from pydantic import BaseModel, Field, field_validator


class NewsItem(BaseModel):
    """Represents a news article from the RSS feed."""

    title: str = Field(description="News article title")
    published_date: date = Field(description="Publication date")
    description: str = Field(default="", description="Article description or summary")
    link: str = Field(default="", description="URL to the full article")


class UpcomingMatch(BaseModel):
    """Represents an upcoming football match from the calendar."""

    home_team: str = Field(description="Home team name")
    away_team: str = Field(description="Away team name")
    match_date: datetime = Field(description="Date and time of the match")
    competition: str = Field(
        default="La Liga", description="Name of the championship/tournament"
    )
    location: str = Field(default="", description="Match venue")
    event_id: str = Field(description="Google Calendar event ID")
    description: str = Field(default="", description="Current event description")

    @field_validator("home_team", "away_team", mode="before")
    @classmethod
    def normalize_team_name(cls, v: str) -> str:
        """Normalize team names (strip whitespace, capitalize)."""
        return v.strip().title()

    @property
    def match_id(self) -> str:
        """Generate a unique identifier for the match."""
        home = self.home_team.lower().replace(" ", "-")
        away = self.away_team.lower().replace(" ", "-")
        return f"{home}-{away}-{self.match_date.date().isoformat()}"


class PreMatchAnalysis(BaseModel):
    """Pre-match analysis generated by AI with context and predictions."""

    match_id: str = Field(description="Unique identifier of the match")
    analysis_points: list[str] = Field(
        min_length=3,
        max_length=3,
        description="Three key analysis points about the upcoming match",
    )
    tactical_preview: str = Field(
        description="Tactical preview and what to expect from the match"
    )
    generated_at: datetime = Field(
        default_factory=datetime.now,
        description="Timestamp when the analysis was generated",
    )
    model_used: str = Field(description="Language model used for generation")
    inference_source: Literal["local_ollama", "cloudflare_tunnel", "dry_run"] = Field(
        description="Source of the inference"
    )

    @field_validator("analysis_points", mode="before")
    @classmethod
    def ensure_three_analysis_points(cls, v: list[str]) -> list[str]:
        """Ensure exactly three analysis points."""
        if len(v) != 3:
            raise ValueError("Must have exactly three analysis points")
        return v
